"""
Recruit_Ai Computer Vision Engine
=================================

Uses:

    OpenCV
    MediaPipe Tasks API
    YOLO11

IMPORTANT
---------

This file DOES NOT use:

    mp.solutions

It uses the newer:

    mp.tasks
    mp.tasks.vision

Detection events generated by this engine:

    face_detected
    face_not_detected
    multiple_faces_detected
    camera_blocked
    face_detection_failed

    looking_away
    head_pose_warning
    phone_detected
    person_left_frame
    suspicious_movement
"""


from __future__ import annotations


# =========================================================
# STANDARD LIBRARY
# =========================================================

import math
import threading
import time
import urllib.request

from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple


# =========================================================
# THIRD PARTY
# =========================================================

import cv2
import numpy as np
import mediapipe as mp

from ultralytics import YOLO


# =========================================================
# MEDIA PIPE IMPORTS
# =========================================================

BaseOptions = mp.tasks.BaseOptions

VisionRunningMode = (
    mp.tasks.vision.RunningMode
)

FaceLandmarker = (
    mp.tasks.vision.FaceLandmarker
)

FaceLandmarkerOptions = (
    mp.tasks.vision.FaceLandmarkerOptions
)


# =========================================================
# PATHS
# =========================================================

BACKEND_DIR = (
    Path(__file__)
    .resolve()
    .parents[2]
)


MODEL_DIR = (
    BACKEND_DIR /
    "Models"
)


MODEL_DIR.mkdir(
    parents=True,
    exist_ok=True
)


# =========================================================
# MODEL FILES
# =========================================================

FACE_LANDMARKER_MODEL = (
    MODEL_DIR /
    "face_landmarker.task"
)


YOLO_MODEL = (
    BACKEND_DIR /
    "yolo11n.pt"
)


# =========================================================
# OFFICIAL MODEL URLS
# =========================================================

FACE_LANDMARKER_URL = (
    "https://storage.googleapis.com/"
    "mediapipe-models/"
    "face_landmarker/"
    "face_landmarker/"
    "float16/"
    "1/"
    "face_landmarker.task"
)


YOLO_MODEL_URL = (
    "https://github.com/"
    "ultralytics/assets/releases/download/"
    "v8.4.0/"
    "yolo11n.pt"
)


# =========================================================
# YOLO COCO CLASS IDS
# =========================================================

# COCO:
# 0  = person
# 67 = cell phone

PERSON_CLASS_ID = 0

CELL_PHONE_CLASS_ID = 67


# =========================================================
# CV ENGINE
# =========================================================

class CVEngine:
    """
    Recruit_Ai Computer Vision Engine.

    Responsibilities:

    1. Face detection
    2. Multiple-face detection
    3. Face missing detection
    4. Head pose estimation
    5. Looking-away detection
    6. Phone detection
    7. Person-left-frame detection
    8. Suspicious movement detection
    9. Camera/frame validation
    10. Image-bytes processing

    This engine does NOT directly write to MongoDB.

    ComputerVisionService / ProctoringService
    are responsible for recording events.
    """

    # =====================================================
    # INIT
    # =====================================================

    def __init__(
        self,

        yolo_model_path: Optional[str] = None,

        face_model_path: Optional[str] = None,

        face_detection_confidence: float = 0.50,

        yolo_confidence: float = 0.25,

        looking_away_threshold: float = 0.35,

        head_pose_threshold: float = 0.35,

        movement_threshold: float = 0.08,

        yolo_image_size: int = 640,
    ):

        # -------------------------------------------------
        # CONFIGURATION
        # -------------------------------------------------

        self.face_detection_confidence = (
            float(face_detection_confidence)
        )

        self.yolo_confidence = (
            float(yolo_confidence)
        )

        self.looking_away_threshold = (
            float(looking_away_threshold)
        )

        self.head_pose_threshold = (
            float(head_pose_threshold)
        )

        self.movement_threshold = (
            float(movement_threshold)
        )

        self.yolo_image_size = (
            int(yolo_image_size)
        )

        # -------------------------------------------------
        # THREAD LOCK
        # -------------------------------------------------
        #
        # cv_engine is a singleton.
        #
        # Multiple FastAPI requests can reach it
        # at the same time.
        #
        # MediaPipe + previous frame state should
        # not be accessed concurrently.
        #

        self._lock = threading.RLock()

        # -------------------------------------------------
        # PREVIOUS FRAME
        # -------------------------------------------------

        self.previous_gray = None

        # -------------------------------------------------
        # LAST RESULT
        # -------------------------------------------------

        self.last_result: Dict[str, Any] = {}

        # -------------------------------------------------
        # TIMESTAMP
        # -------------------------------------------------

        self.last_timestamp = 0.0

        # -------------------------------------------------
        # FACE MODEL PATH
        # -------------------------------------------------

        self.face_model_path = (
            Path(face_model_path)
            if face_model_path
            else FACE_LANDMARKER_MODEL
        )

        # -------------------------------------------------
        # ENSURE FACE MODEL
        # -------------------------------------------------

        self._ensure_face_model()

        # -------------------------------------------------
        # CREATE FACE LANDMARKER
        # -------------------------------------------------

        self.face_landmarker = (
            self._create_face_landmarker()
        )

        # -------------------------------------------------
        # YOLO MODEL PATH
        # -------------------------------------------------

        self.yolo_model_path = (
            Path(yolo_model_path)
            if yolo_model_path
            else YOLO_MODEL
        )

        # -------------------------------------------------
        # ENSURE YOLO MODEL
        # -------------------------------------------------

        self._ensure_yolo_model()

        # -------------------------------------------------
        # LOAD YOLO
        # -------------------------------------------------

        self.yolo = YOLO(
            str(self.yolo_model_path)
        )

        print(
            "========================================"
        )
        print(
            "Recruit_Ai CV Engine initialized"
        )
        print(
            f"Face model: {self.face_model_path}"
        )
        print(
            f"YOLO model: {self.yolo_model_path}"
        )
        print(
            "========================================"
        )

    # =====================================================
    # DOWNLOAD FILE
    # =====================================================

    @staticmethod
    def _download_file(
        url: str,
        destination: Path
    ) -> None:

        destination.parent.mkdir(
            parents=True,
            exist_ok=True
        )

        print(
            "========================================"
        )

        print(
            "Downloading model:"
        )

        print(url)

        print(
            f"Destination: {destination}"
        )

        print(
            "========================================"
        )

        try:

            urllib.request.urlretrieve(
                url,
                str(destination)
            )

        except Exception as exc:

            if destination.exists():

                try:
                    destination.unlink()
                except Exception:
                    pass

            raise RuntimeError(
                f"Failed to download model: {exc}"
            ) from exc

    # =====================================================
    # ENSURE FACE MODEL
    # =====================================================

    def _ensure_face_model(
        self
    ) -> None:

        if (
            self.face_model_path.exists()
            and
            self.face_model_path.stat().st_size > 0
        ):

            print(
                "MediaPipe face model found:"
            )

            print(
                self.face_model_path
            )

            return

        print(
            "MediaPipe face model not found."
        )

        self._download_file(
            FACE_LANDMARKER_URL,
            self.face_model_path
        )

        if (
            not self.face_model_path.exists()
            or
            self.face_model_path.stat().st_size == 0
        ):

            raise RuntimeError(
                "MediaPipe face landmark model "
                "was not downloaded."
            )

    # =====================================================
    # ENSURE YOLO MODEL
    # =====================================================

    def _ensure_yolo_model(
        self
    ) -> None:

        if (
            self.yolo_model_path.exists()
            and
            self.yolo_model_path.stat().st_size > 0
        ):

            print(
                "YOLO model found:"
            )

            print(
                self.yolo_model_path
            )

            return

        print(
            "YOLO model not found."
        )

        self._download_file(
            YOLO_MODEL_URL,
            self.yolo_model_path
        )

        if (
            not self.yolo_model_path.exists()
            or
            self.yolo_model_path.stat().st_size == 0
        ):

            raise RuntimeError(
                "YOLO model was not downloaded."
            )

    # =====================================================
    # CREATE FACE LANDMARKER
    # =====================================================

    def _create_face_landmarker(
        self
    ):

        options = FaceLandmarkerOptions(

            base_options=BaseOptions(
                model_asset_path=(
                    str(
                        self.face_model_path
                    )
                )
            ),

            running_mode=(
                VisionRunningMode.IMAGE
            ),

            num_faces=5,

            min_face_detection_confidence=(
                self.face_detection_confidence
            ),

            min_face_presence_confidence=(
                self.face_detection_confidence
            ),

            min_tracking_confidence=(
                self.face_detection_confidence
            ),

            output_face_blendshapes=True,

            output_facial_transformation_matrixes=True
        )

        return FaceLandmarker.create_from_options(
            options
        )

    # =====================================================
    # CLOSE
    # =====================================================

    def close(
        self
    ) -> None:

        try:

            if self.face_landmarker:

                self.face_landmarker.close()

        except Exception as exc:

            print(
                "CV engine close warning:",
                exc
            )

    # =====================================================
    # DESTRUCTOR
    # =====================================================

    def __del__(
        self
    ):

        try:

            self.close()

        except Exception:

            pass

    # =====================================================
    # OPENCV -> MEDIAPIPE IMAGE
    # =====================================================

    @staticmethod
    def _to_mp_image(
        frame: np.ndarray
    ):

        rgb = cv2.cvtColor(
            frame,
            cv2.COLOR_BGR2RGB
        )

        return mp.Image(
            image_format=(
                mp.ImageFormat.SRGB
            ),
            data=rgb
        )

    # =====================================================
    # SAFE FRAME CHECK
    # =====================================================

    @staticmethod
    def _validate_frame(
        frame: Any
    ) -> bool:

        if frame is None:

            return False

        if not isinstance(
            frame,
            np.ndarray
        ):

            return False

        if frame.size <= 0:

            return False

        if len(
            frame.shape
        ) < 2:

            return False

        height, width = (
            frame.shape[:2]
        )

        if (
            height <= 0
            or
            width <= 0
        ):

            return False

        return True

    # =====================================================
    # PROCESS IMAGE BYTES
    # =====================================================

    def process_image_bytes(
        self,
        image_bytes: bytes
    ) -> Dict[str, Any]:
        """
        Process uploaded JPEG/PNG/WEBP bytes.

        Flow:

            bytes
              ↓
            numpy
              ↓
            OpenCV decode
              ↓
            process_frame()
        """

        timestamp = time.time()

        # -------------------------------------------------
        # EMPTY IMAGE
        # -------------------------------------------------

        if not image_bytes:

            result = {

                "success": False,

                "camera_blocked": True,

                "face_detection_failed": False,

                "events": [

                    {
                        "event_type":
                            "camera_blocked",

                        "severity":
                            "high",

                        "message":
                            "Uploaded camera image is empty.",

                        "metadata": {}
                    }

                ],

                "timestamp":
                    timestamp
            }

            self.last_result = result

            return result

        try:

            # -------------------------------------------------
            # BYTES -> NUMPY
            # -------------------------------------------------

            image_array = np.frombuffer(
                image_bytes,
                dtype=np.uint8
            )

            if image_array.size == 0:

                raise ValueError(
                    "Image byte buffer is empty."
                )

            # -------------------------------------------------
            # NUMPY -> OPENCV IMAGE
            # -------------------------------------------------

            frame = cv2.imdecode(
                image_array,
                cv2.IMREAD_COLOR
            )

            if frame is None:

                raise ValueError(
                    "OpenCV could not decode "
                    "the uploaded image."
                )

            # -------------------------------------------------
            # PROCESS
            # -------------------------------------------------

            return self.process_frame(
                frame
            )

        except Exception as exc:

            print(
                "========================================"
            )

            print(
                "CV IMAGE PROCESSING ERROR"
            )

            print(
                repr(exc)
            )

            print(
                "========================================"
            )

            result = {

                "success": False,

                "camera_blocked": False,

                "face_detection_failed": True,

                "events": [

                    {
                        "event_type":
                            "face_detection_failed",

                        "severity":
                            "high",

                        "message":
                            "Computer vision image processing failed.",

                        "metadata": {

                            "error":
                                str(exc)
                        }
                    }

                ],

                "timestamp":
                    timestamp
            }

            self.last_result = result

            return result

    # =====================================================
    # ALIAS
    # =====================================================

    def process_bytes(
        self,
        image_bytes: bytes
    ) -> Dict[str, Any]:

        return self.process_image_bytes(
            image_bytes
        )

    # =====================================================
    # FACE DETECTION
    # =====================================================

    def _detect_faces(
        self,
        frame: np.ndarray
    ) -> Dict[str, Any]:

        result = {

            "face_count": 0,

            "face_landmarks": [],

            "face_boxes": [],

            "face_detected": False,

            "multiple_faces": False,

            "error": None
        }

        try:

            # -------------------------------------------------
            # CONVERT TO MEDIAPIPE IMAGE
            # -------------------------------------------------

            mp_image = (
                self._to_mp_image(
                    frame
                )
            )

            # -------------------------------------------------
            # RUN FACE LANDMARKER
            # -------------------------------------------------

            detection_result = (
                self.face_landmarker.detect(
                    mp_image
                )
            )

            landmarks = (
                detection_result.face_landmarks
                or []
            )

            face_count = len(
                landmarks
            )

            result[
                "face_count"
            ] = face_count

            result[
                "face_landmarks"
            ] = landmarks

            result[
                "face_detected"
            ] = (
                face_count > 0
            )

            result[
                "multiple_faces"
            ] = (
                face_count > 1
            )

            # -------------------------------------------------
            # FACE BOXES
            # -------------------------------------------------

            height, width = (
                frame.shape[:2]
            )

            boxes = []

            for face in landmarks:

                if not face:

                    continue

                xs = [
                    float(point.x)
                    for point in face
                    if point is not None
                ]

                ys = [
                    float(point.y)
                    for point in face
                    if point is not None
                ]

                if not xs or not ys:

                    continue

                x1 = max(
                    0,
                    int(
                        min(xs)
                        * width
                    )
                )

                y1 = max(
                    0,
                    int(
                        min(ys)
                        * height
                    )
                )

                x2 = min(
                    width - 1,
                    int(
                        max(xs)
                        * width
                    )
                )

                y2 = min(
                    height - 1,
                    int(
                        max(ys)
                        * height
                    )
                )

                if x2 > x1 and y2 > y1:

                    boxes.append(
                        [
                            x1,
                            y1,
                            x2,
                            y2
                        ]
                    )

            result[
                "face_boxes"
            ] = boxes

        except Exception as exc:

            result[
                "error"
            ] = str(exc)

        return result

    # =====================================================
    # FACE CENTER
    # =====================================================

    @staticmethod
    def _face_center(
        landmarks
    ) -> Optional[
        Tuple[float, float]
    ]:

        if not landmarks:

            return None

        xs = [
            float(point.x)
            for point in landmarks
            if point is not None
        ]

        ys = [
            float(point.y)
            for point in landmarks
            if point is not None
        ]

        if not xs or not ys:

            return None

        return (
            sum(xs) / len(xs),
            sum(ys) / len(ys)
        )

    # =====================================================
    # HEAD POSE
    # =====================================================

    def _estimate_head_pose(
        self,
        landmarks
    ) -> Dict[str, Any]:

        """
        Approximate head orientation.

        This uses normalized facial landmark geometry.

        It intentionally does not use:

            mp.solutions.face_mesh
        """

        result = {

            "looking_away": False,

            "head_pose_warning": False,

            "yaw": 0.0,

            "pitch": 0.0,

            "roll": 0.0
        }

        if not landmarks:

            return result

        try:

            # -------------------------------------------------
            # REQUIRED LANDMARKS
            # -------------------------------------------------

            if len(landmarks) <= 291:

                return result

            nose = landmarks[1]

            left_eye = landmarks[33]

            right_eye = landmarks[263]

            chin = landmarks[152]

            # -------------------------------------------------
            # EYE CENTER
            # -------------------------------------------------

            eye_center_x = (
                float(left_eye.x)
                +
                float(right_eye.x)
            ) / 2.0

            eye_center_y = (
                float(left_eye.y)
                +
                float(right_eye.y)
            ) / 2.0

            # -------------------------------------------------
            # EYE DISTANCE
            # -------------------------------------------------

            eye_distance = math.sqrt(

                (
                    float(right_eye.x)
                    -
                    float(left_eye.x)
                ) ** 2

                +

                (
                    float(right_eye.y)
                    -
                    float(left_eye.y)
                ) ** 2
            )

            if eye_distance < 0.001:

                return result

            # -------------------------------------------------
            # YAW
            # -------------------------------------------------
            #
            # Normalized horizontal nose displacement.
            #

            yaw = (
                float(nose.x)
                -
                eye_center_x
            ) / eye_distance

            # -------------------------------------------------
            # PITCH
            # -------------------------------------------------

            vertical_face_distance = (
                float(chin.y)
                -
                eye_center_y
            )

            if abs(
                vertical_face_distance
            ) < 0.001:

                vertical_face_distance = 0.001

            pitch = (

                (
                    float(nose.y)
                    -
                    eye_center_y
                )

                /

                vertical_face_distance
            )

            # -------------------------------------------------
            # ROLL
            # -------------------------------------------------

            roll = math.atan2(

                float(right_eye.y)
                -
                float(left_eye.y),

                float(right_eye.x)
                -
                float(left_eye.x)
            )

            roll_degrees = (
                math.degrees(roll)
            )

            # -------------------------------------------------
            # STORE
            # -------------------------------------------------

            result[
                "yaw"
            ] = round(
                float(yaw),
                4
            )

            result[
                "pitch"
            ] = round(
                float(pitch),
                4
            )

            result[
                "roll"
            ] = round(
                float(roll_degrees),
                2
            )

            # -------------------------------------------------
            # LOOKING AWAY
            # -------------------------------------------------

            looking_away = (
                abs(yaw)
                >
                self.looking_away_threshold
            )

            # -------------------------------------------------
            # HEAD POSE WARNING
            # -------------------------------------------------

            head_pose_warning = (

                abs(yaw)
                >
                self.head_pose_threshold

                or

                abs(roll_degrees)
                >
                25.0
            )

            result[
                "looking_away"
            ] = bool(
                looking_away
            )

            result[
                "head_pose_warning"
            ] = bool(
                head_pose_warning
            )

        except Exception as exc:

            print(
                "Head pose calculation error:",
                exc
            )

        return result

    # =====================================================
    # YOLO OBJECT DETECTION
    # =====================================================

    def _detect_objects(
        self,
        frame: np.ndarray
    ) -> Dict[str, Any]:

        result = {

            "person_count": 0,

            "phone_detected": False,

            "person_boxes": [],

            "phone_boxes": [],

            "detections": [],

            "error": None
        }

        try:

            # -------------------------------------------------
            # YOLO PREDICTION
            # -------------------------------------------------

            predictions = self.yolo.predict(

                source=frame,

                conf=(
                    self.yolo_confidence
                ),

                imgsz=(
                    self.yolo_image_size
                ),

                verbose=False,

                device="cpu"
            )

            if not predictions:

                return result

            prediction = predictions[0]

            boxes = prediction.boxes

            if boxes is None:

                return result

            names = (
                prediction.names
                or {}
            )

            # -------------------------------------------------
            # LOOP DETECTIONS
            # -------------------------------------------------

            for box in boxes:

                try:

                    class_id = int(
                        box.cls[0].item()
                    )

                    confidence = float(
                        box.conf[0].item()
                    )

                    coordinates = (
                        box.xyxy[0].tolist()
                    )

                    x1, y1, x2, y2 = (
                        [
                            int(value)
                            for value
                            in coordinates
                        ]
                    )

                    class_name = (
                        names.get(
                            class_id,
                            str(class_id)
                        )
                    )

                    detection = {

                        "class_id":
                            class_id,

                        "class_name":
                            class_name,

                        "confidence":
                            round(
                                confidence,
                                4
                            ),

                        "box": [
                            x1,
                            y1,
                            x2,
                            y2
                        ]
                    }

                    result[
                        "detections"
                    ].append(
                        detection
                    )

                    # -----------------------------------------
                    # PERSON
                    # -----------------------------------------

                    if (
                        class_id
                        ==
                        PERSON_CLASS_ID
                    ):

                        result[
                            "person_count"
                        ] += 1

                        result[
                            "person_boxes"
                        ].append(
                            [
                                x1,
                                y1,
                                x2,
                                y2
                            ]
                        )

                    # -----------------------------------------
                    # CELL PHONE
                    # -----------------------------------------

                    if (
                        class_id
                        ==
                        CELL_PHONE_CLASS_ID
                    ):

                        result[
                            "phone_detected"
                        ] = True

                        result[
                            "phone_boxes"
                        ].append(
                            [
                                x1,
                                y1,
                                x2,
                                y2
                            ]
                        )

                except Exception as exc:

                    print(
                        "YOLO detection parsing error:",
                        exc
                    )

                    continue

        except Exception as exc:

            result[
                "error"
            ] = str(exc)

            print(
                "YOLO processing error:",
                exc
            )

        return result

    # =====================================================
    # MOVEMENT DETECTION
    # =====================================================

    def _detect_movement(
        self,
        frame: np.ndarray
    ) -> Dict[str, Any]:

        result = {

            "suspicious_movement":
                False,

            "movement_score":
                0.0
        }

        try:

            gray = cv2.cvtColor(
                frame,
                cv2.COLOR_BGR2GRAY
            )

            gray = cv2.resize(
                gray,
                (
                    320,
                    240
                )
            )

            gray = cv2.GaussianBlur(
                gray,
                (
                    21,
                    21
                ),
                0
            )

            # -------------------------------------------------
            # FIRST FRAME
            # -------------------------------------------------

            if self.previous_gray is None:

                self.previous_gray = gray

                return result

            # -------------------------------------------------
            # FRAME DIFFERENCE
            # -------------------------------------------------

            difference = cv2.absdiff(
                self.previous_gray,
                gray
            )

            _, threshold = cv2.threshold(
                difference,
                25,
                255,
                cv2.THRESH_BINARY
            )

            movement_pixels = (
                np.count_nonzero(
                    threshold
                )
            )

            total_pixels = (
                threshold.shape[0]
                *
                threshold.shape[1]
            )

            movement_score = (
                movement_pixels
                /
                max(
                    total_pixels,
                    1
                )
            )

            self.previous_gray = gray

            result[
                "movement_score"
            ] = round(
                float(
                    movement_score
                ),
                4
            )

            result[
                "suspicious_movement"
            ] = (
                movement_score
                >
                self.movement_threshold
            )

        except Exception as exc:

            print(
                "Movement detection error:",
                exc
            )

        return result

    # =====================================================
    # PERSON LEFT FRAME
    # =====================================================

    @staticmethod
    def _person_left_frame(
        person_count: int,
        face_count: int
    ) -> bool:

        if (
            person_count == 0
            and
            face_count == 0
        ):

            return True

        return False

    # =====================================================
    # BUILD FACE EVENTS
    # =====================================================

    def _build_face_events(
        self,
        face_result: Dict[str, Any]
    ) -> List[Dict[str, Any]]:

        events = []

        face_count = int(
            face_result.get(
                "face_count",
                0
            )
        )

        face_error = (
            face_result.get(
                "error"
            )
        )

        # -------------------------------------------------
        # FACE ENGINE ERROR
        # -------------------------------------------------

        if face_error:

            events.append({

                "event_type":
                    "face_detection_failed",

                "severity":
                    "medium",

                "message":
                    "Computer vision face detection failed.",

                "metadata": {

                    "error":
                        face_error
                }
            })

            return events

        # -------------------------------------------------
        # ONE FACE
        # -------------------------------------------------

        if face_count == 1:

            events.append({

                "event_type":
                    "face_detected",

                "severity":
                    "low",

                "message":
                    "Candidate face detected.",

                "metadata": {

                    "face_count":
                        face_count
                }
            })

        # -------------------------------------------------
        # NO FACE
        # -------------------------------------------------

        elif face_count == 0:

            events.append({

                "event_type":
                    "face_not_detected",

                "severity":
                    "medium",

                "message":
                    "Candidate face was not detected.",

                "metadata": {

                    "face_count":
                        0
                }
            })

        # -------------------------------------------------
        # MULTIPLE FACES
        # -------------------------------------------------

        elif face_count > 1:

            events.append({

                "event_type":
                    "multiple_faces_detected",

                "severity":
                    "high",

                "message":
                    "Multiple faces detected in the interview frame.",

                "metadata": {

                    "face_count":
                        face_count
                }
            })

        return events

    # =====================================================
    # PROCESS FRAME
    # =====================================================

    def process_frame(
        self,
        frame: np.ndarray
    ) -> Dict[str, Any]:

        """
        Main CV processing pipeline.

        Input:

            OpenCV BGR frame.

        Output:

            Detection dictionary.
        """

        timestamp = time.time()

        # =================================================
        # THREAD SAFETY
        # =================================================

        with self._lock:

            # =============================================
            # INVALID FRAME
            # =============================================

            if not self._validate_frame(
                frame
            ):

                result = {

                    "success":
                        False,

                    "timestamp":
                        timestamp,

                    "camera_blocked":
                        True,

                    "face_detection_failed":
                        False,

                    "face_count":
                        0,

                    "person_count":
                        0,

                    "phone_detected":
                        False,

                    "movement_score":
                        0.0,

                    "events": [

                        {
                            "event_type":
                                "camera_blocked",

                            "severity":
                                "high",

                            "message":
                                "Camera frame is unavailable.",

                            "metadata": {}
                        }

                    ],

                    "face_boxes": [],

                    "person_boxes": [],

                    "phone_boxes": [],

                    "detections": []
                }

                self.last_result = result

                return result

            # =============================================
            # FACE
            # =============================================

            face_result = (
                self._detect_faces(
                    frame
                )
            )

            face_count = int(
                face_result.get(
                    "face_count",
                    0
                )
            )

            # =============================================
            # OBJECTS
            # =============================================

            object_result = (
                self._detect_objects(
                    frame
                )
            )

            person_count = int(
                object_result.get(
                    "person_count",
                    0
                )
            )

            # =============================================
            # MOVEMENT
            # =============================================

            movement_result = (
                self._detect_movement(
                    frame
                )
            )

            # =============================================
            # EVENTS
            # =============================================

            events: List[
                Dict[str, Any]
            ] = []

            # =============================================
            # FACE EVENTS
            # =============================================

            events.extend(
                self._build_face_events(
                    face_result
                )
            )

            # =============================================
            # HEAD POSE
            # =============================================

            pose_result = {

                "looking_away": False,

                "head_pose_warning": False,

                "yaw": 0.0,

                "pitch": 0.0,

                "roll": 0.0
            }

            if (
                face_count >= 1
                and
                face_result.get(
                    "face_landmarks"
                )
            ):

                landmarks = (
                    face_result[
                        "face_landmarks"
                    ][0]
                )

                pose_result = (
                    self._estimate_head_pose(
                        landmarks
                    )
                )

                # -----------------------------------------
                # LOOKING AWAY
                # -----------------------------------------

                if pose_result.get(
                    "looking_away",
                    False
                ):

                    events.append({

                        "event_type":
                            "looking_away",

                        "severity":
                            "medium",

                        "message":
                            "Candidate appears to be looking away from the screen.",

                        "metadata": {

                            "yaw":
                                pose_result[
                                    "yaw"
                                ],

                            "pitch":
                                pose_result[
                                    "pitch"
                                ],

                            "roll":
                                pose_result[
                                    "roll"
                                ]
                        }
                    })

                # -----------------------------------------
                # HEAD POSE
                # -----------------------------------------

                if pose_result.get(
                    "head_pose_warning",
                    False
                ):

                    events.append({

                        "event_type":
                            "head_pose_warning",

                        "severity":
                            "medium",

                        "message":
                            "Candidate head pose indicates suspicious orientation.",

                        "metadata": {

                            "yaw":
                                pose_result[
                                    "yaw"
                                ],

                            "pitch":
                                pose_result[
                                    "pitch"
                                ],

                            "roll":
                                pose_result[
                                    "roll"
                                ]
                        }
                    })

            # =============================================
            # PHONE
            # =============================================

            phone_detected = bool(
                object_result.get(
                    "phone_detected",
                    False
                )
            )

            if phone_detected:

                events.append({

                    "event_type":
                        "phone_detected",

                    "severity":
                        "high",

                    "message":
                        "Possible mobile phone detected in the interview frame.",

                    "metadata": {

                        "phone_boxes":
                            object_result.get(
                                "phone_boxes",
                                []
                            )
                    }
                })

            # =============================================
            # PERSON LEFT FRAME
            # =============================================

            person_left = (
                self._person_left_frame(
                    person_count,
                    face_count
                )
            )

            if person_left:

                events.append({

                    "event_type":
                        "person_left_frame",

                    "severity":
                        "high",

                    "message":
                        "Candidate appears to have left the camera frame.",

                    "metadata": {

                        "person_count":
                            person_count,

                        "face_count":
                            face_count
                    }
                })

            # =============================================
            # SUSPICIOUS MOVEMENT
            # =============================================

            suspicious_movement = bool(
                movement_result.get(
                    "suspicious_movement",
                    False
                )
            )

            if suspicious_movement:

                events.append({

                    "event_type":
                        "suspicious_movement",

                    "severity":
                        "medium",

                    "message":
                        "Suspicious movement detected in the interview frame.",

                    "metadata": {

                        "movement_score":
                            movement_result.get(
                                "movement_score",
                                0.0
                            )
                    }
                })

            # =============================================
            # YOLO ERROR
            # =============================================

            yolo_error = (
                object_result.get(
                    "error"
                )
            )

            # We don't create a new event type here
            # because your existing event system does not
            # list "yolo_detection_failed".
            #
            # The error is returned in diagnostics instead.

            # =============================================
            # CAMERA BLOCKED
            # =============================================

            camera_blocked = False

            if frame is None:

                camera_blocked = True

                events.append({

                    "event_type":
                        "camera_blocked",

                    "severity":
                        "high",

                    "message":
                        "Camera appears to be blocked or unavailable.",

                    "metadata": {}
                })

            # =============================================
            # BUILD RESULT
            # =============================================

            result = {

                "success":
                    True,

                "timestamp":
                    timestamp,

                # -----------------------------------------
                # FACE
                # -----------------------------------------

                "face_count":
                    face_count,

                "face_detected":
                    face_count > 0,

                "multiple_faces":
                    face_count > 1,

                "face_detection_failed":
                    bool(
                        face_result.get(
                            "error"
                        )
                    ),

                # -----------------------------------------
                # PERSON
                # -----------------------------------------

                "person_count":
                    person_count,

                "person_detected":
                    person_count > 0,

                "person_left_frame":
                    person_left,

                # -----------------------------------------
                # PHONE
                # -----------------------------------------

                "phone_detected":
                    phone_detected,

                # -----------------------------------------
                # CAMERA
                # -----------------------------------------

                "camera_blocked":
                    camera_blocked,

                # -----------------------------------------
                # MOVEMENT
                # -----------------------------------------

                "movement_score":
                    movement_result.get(
                        "movement_score",
                        0.0
                    ),

                "suspicious_movement":
                    suspicious_movement,

                # -----------------------------------------
                # HEAD POSE
                # -----------------------------------------

                "looking_away":
                    bool(
                        pose_result.get(
                            "looking_away",
                            False
                        )
                    ),

                "head_pose_warning":
                    bool(
                        pose_result.get(
                            "head_pose_warning",
                            False
                        )
                    ),

                "yaw":
                    pose_result.get(
                        "yaw",
                        0.0
                    ),

                "pitch":
                    pose_result.get(
                        "pitch",
                        0.0
                    ),

                "roll":
                    pose_result.get(
                        "roll",
                        0.0
                    ),

                # -----------------------------------------
                # EVENTS
                # -----------------------------------------

                "events":
                    events,

                # -----------------------------------------
                # BOXES
                # -----------------------------------------

                "face_boxes":
                    face_result.get(
                        "face_boxes",
                        []
                    ),

                "person_boxes":
                    object_result.get(
                        "person_boxes",
                        []
                    ),

                "phone_boxes":
                    object_result.get(
                        "phone_boxes",
                        []
                    ),

                # -----------------------------------------
                # YOLO DETECTIONS
                # -----------------------------------------

                "detections":
                    object_result.get(
                        "detections",
                        []
                    ),

                # -----------------------------------------
                # DIAGNOSTICS
                # -----------------------------------------

                "diagnostics": {

                    "face_error":
                        face_result.get(
                            "error"
                        ),

                    "yolo_error":
                        yolo_error,

                    "yolo_confidence":
                        self.yolo_confidence,

                    "yolo_image_size":
                        self.yolo_image_size,

                    "face_confidence":
                        self.face_detection_confidence
                }
            }

            # =============================================
            # SAVE LAST RESULT
            # =============================================

            self.last_result = result

            self.last_timestamp = (
                timestamp
            )

            return result

    # =====================================================
    # DETECT
    # =====================================================

    def detect(
        self,
        frame: np.ndarray
    ) -> Dict[str, Any]:

        return self.process_frame(
            frame
        )

    # =====================================================
    # GET EVENTS ONLY
    # =====================================================

    def get_events(
        self,
        frame: np.ndarray
    ) -> List[
        Dict[str, Any]
    ]:

        result = (
            self.process_frame(
                frame
            )
        )

        return result.get(
            "events",
            []
        )

    # =====================================================
    # HEALTH CHECK
    # =====================================================

    def health(
        self
    ) -> Dict[str, Any]:

        return {

            "success":
                True,

            "engine":
                "CVEngine",

            # ---------------------------------------------
            # LIBRARIES
            # ---------------------------------------------

            "opencv":
                cv2.__version__,

            "mediapipe":
                getattr(
                    mp,
                    "__version__",
                    "unknown"
                ),

            "mediapipe_tasks":
                hasattr(
                    mp,
                    "tasks"
                ),

            "yolo":
                True,

            # ---------------------------------------------
            # MODELS
            # ---------------------------------------------

            "face_model":
                str(
                    self.face_model_path
                ),

            "face_model_exists":
                (
                    self.face_model_path.exists()
                    and
                    self.face_model_path.stat().st_size > 0
                ),

            "yolo_model":
                str(
                    self.yolo_model_path
                ),

            "yolo_model_exists":
                (
                    self.yolo_model_path.exists()
                    and
                    self.yolo_model_path.stat().st_size > 0
                ),

            # ---------------------------------------------
            # CONFIG
            # ---------------------------------------------

            "face_confidence":
                self.face_detection_confidence,

            "yolo_confidence":
                self.yolo_confidence,

            "looking_away_threshold":
                self.looking_away_threshold,

            "head_pose_threshold":
                self.head_pose_threshold,

            "movement_threshold":
                self.movement_threshold,

            "yolo_image_size":
                self.yolo_image_size,

            # ---------------------------------------------
            # LAST PROCESSING
            # ---------------------------------------------

            "last_timestamp":
                self.last_timestamp,

            "last_result_available":
                bool(
                    self.last_result
                )
        }


# =========================================================
# SINGLETON
# =========================================================

cv_engine = CVEngine()